language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=4
before_install:
    - which firefox
    - npm i -g npm@2.15.5
install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install
cache:
  directories:
    - node_modules
addons:
  firefox: "49.0"
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm run serve &
    - sleep 15 # give Web server some time to bind to sockets, etc
script:
  # - npm test
  - npm run test:functional
