language: node_js
node_js:
    - "4"
sudo: false
before_install: npm i -g npm@2.15.5
cache:
    directories:
        - node_modules
before_script:
    - printenv
    - npm run serve &
    - sleep 5 # give Web server some time to bind to sockets, etc
script:
    # - npm test
    - npm run test:functional
addons:
  sauce_connect:
    username: "riscarrott"
  jwt:
    secure: "voU9xvKB7SKwPQO/SEyBqLu+tAHtUST8pC70TlcbUYz82J46xWzIL+Wo4se3S1xVfOgRDcRM3gKs94cJlAEzka8hYxio0KMpF2p1OXg9FwgjmUx1qACAfig+mL/fX3Gf/usvBZJcuGkJWzEO3a9d6CAb0YHV9mo3VKWkEd/u2FXjc+P2GBR3nXJkZpMkXr2ycDUmeljv/75OZbbuCJGOEogkDzJL5+2dsUGdhHn4sBH1KWza3qP7dgcr1/jIuQe1BZeDwMFFvYsTLEs5mEu4MM70Lg2WfmkriEG1zC8QGAvb0dlO90H5b4j0irHHM1Fz/FXcazNRKGbikJfXcQxUL1JtN+D+Tla3OjoN/6iGPsf+L7YLr10eshOOAl5XwNiffi+S12+ijI6Y5aQTA+auk8LUeQ4cM3sdRIwGoew7ccK81DCkORKDm5smpcOfg5c3HzqxylZvjXhyyH549bnbJJCf8HTvJvghP21wi+72P1vPalaNEEv0i5UPv/4dvw4ivAVCl6O1WGKOfaK0JOyFGtwkVWipOKJH5I5VRj8AGT4JL3HnFN3PxoX1o3OGolcn8BHQJGtUKjO0jWKwEGReIyGFME6vbTHE7/xOn6o6PATzXUBjaK7QPlUyhFvve2z2gj/O6ee9pL1ohBjbBELiyJwOE4SzphxDXDXLM+93qFE="

    # addons: {
    #     browserstack: {
    #         username: "http://richardscarrott1.browserstack.com",
    #         access_key: {
    #             secure: "PU/TBMDvDIOmP07kciQ8gIJ1ALjKaCBg5j6w6VtlCa3DmC1ySuA2HH5+/3dODSUqt30nmQpYX16MiS94nVrp23PevGVTLLV2BtBgvOzSL7TlTOfE2JGQvx3zfQ0qOZEE5XfHaoyzZqi7h5VF5ltlAUjFH5QKg/pzGRmyQdgAHV4D96exB2FQ83LeSYBnFCqtnuowUeFeIFB3gciCWow3Lzo5p4Wz+WtFKRkMRzkecsKmpuVtB7HaVUm1iWFUQlhpBzaXQz+mSvlwz7t4e6dA8J5mJTSMFgKrzSHtATj/vUBnCANpTX7tA4ODa5dsoel1WNbx4c2yjWq5Rsk4pdtQ+EvsWN+twVdKv+isPYVSggf63UYClZxov4BxrhX46toVn3xwCBaILe6giywjA6TmT2xeF/ajenGCigdzeQy+FpX/x9kLYoOBePuUgGEYiAjgI1b/1DORBUBJgLztd5h2yFVxSmSIyKUGEPgmhxq4eM9RvbU2Gplu1qlHVFC+T2Bwt0UIHNcHr8yaLF3cz+BSnOo5e5HorEPq+cS1rQMAb4B4EDedQOnUqnA48muHCKF0BgYu1VeahE461BH9WDBWJb/VU4NdXvWD+7wTAQ8MrmIKjLtFg6nODPoVJ/CJlpEhNOuPcYnwqhweuvNzJ5XYmb0s/5xta/Dc0HmiTsD2Bn4="
    #         }
    #     }
    # }
