language: node_js
node_js:
  - "4"
sudo: false
before_install: npm i -g npm@2.15.5
cache:
  directories:
    - node_modules
before_script:
    - npm run serve &
    - sleep 3 # give Web server some time to bind to sockets, etc
script:
    - npm test
    - npm run test:functional
