export {default as H1} from './h1/H1';
export {default as H2} from './h2/H2';
export {default as H3} from './h3/H3';
export {default as H4} from './h4/H4';
export {default as IntroText} from './introtext/IntroText';
export {default as BodyText} from './bodytext/BodyText';
export {default as Quote} from './quote/Quote';
export {default as ActionText} from './actiontext/ActionText';
export {default as Code} from './code/Code';
export {default as List} from './list/List';
// export {default as SmallText} from './smalltext/SmallText';
export {default as Copy} from './copy/Copy';
