export { default as H1 } from 'components/lib/typography/h1/H1';
export { default as H2 } from 'components/lib/typography/h2/H2';
export { default as H3 } from 'components/lib/typography/h3/H3';
export { default as H4 } from 'components/lib/typography/h4/H4';
export { default as IntroText } from 'components/lib/typography/introtext/IntroText';
export { default as BodyText } from 'components/lib/typography/bodytext/BodyText';
export { default as Quote } from 'components/lib/typography/quote/Quote';
export { default as ActionText } from 'components/lib/typography/actiontext/ActionText';
export { default as Code } from 'components/lib/typography/code/Code';
export { default as List } from 'components/lib/typography/list/List';
export { default as InlineCode } from 'components/lib/typography/inlinecode/InlineCode';
// export { default as SmallText } from 'components/lib/typography/smalltext/SmallText';
export { default as Copy } from 'components/lib/typography/copy/Copy';
